c_compiler:    # [win]
- vs2022       # [win]
cxx_compiler:  # [win]
- vs2022       # [win]
# Workaround forcing cxx_compiler_version, see https://github.com/conda-forge/pyobjcryst-feedstock/pull/43#issuecomment-2335172380 and https://github.com/conda-forge/admin-requests/pull/1062
cxx_compiler_version:  # [win]
  - 19.40          # [win]
