{% set name = "pyobjcryst" %}
{% set version = "2.1.0" %}
{% set sha256 = "930c51f221cbc8895d7bde152f134ad26269ceb666415fa8b701e5cd369a9dbb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or py2k]
  script: python setup.py install

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - libobjcryst 2017.1.*
    - boost
  run:
    # NOTE libobjcryst is implicitly added by libobjcryst run_exports
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - boost

test:
  imports:
    - pyobjcryst
    - pyobjcryst.tests

about:
  home: https://github.com/diffpy/pyobjcryst
  license: BNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python bindings to the ObjCryst++ crystallographic library.'
  doc_url: http://diffpy.github.io/pyobjcryst
  dev_url: https://github.com/diffpy/pyobjcryst

extra:
  recipe-maintainers:
    - CJ-Wright
    - pavoljuhas
