{% set name = "pyobjcryst" %}
{% set version = "2.1.0.post2" %}
{% set sha256 = "2ee797cf4d0ba90a7d144110b0f3295ee7fa73462c648297100bfd5eb467bb6d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - scattering.patch
    - boostpythonsuffixes.patch
    - unitcell.patch

build:
  number: 0
  skip: True  # [win or py2k]
  script: python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - libobjcryst 2017.1.*
    - boost
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - libobjcryst 2017.1.*
    - boost

test:
  imports:
    - pyobjcryst
    - pyobjcryst.tests

about:
  home: https://github.com/diffpy/pyobjcryst
  license: BNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python bindings to the ObjCryst++ crystallographic library.'
  doc_url: http://diffpy.github.io/pyobjcryst
  dev_url: https://github.com/diffpy/pyobjcryst

extra:
  recipe-maintainers:
    - CJ-Wright
    - pavoljuhas
