{% set name = "pyobjcryst" %}
{% set version = "2025.1.0" %}
{% set sha256 = "782c776de91d815cf74aff865fe002db99eff83a786c684dc9324460cd5fed5f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<311]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools-git-versioning
    - numpy
    - libobjcryst 2024.2.1
    - libboost-python-devel
  run:
    - python
    - setuptools

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/diffpy/pyobjcryst
  license: LicenseRef-diffpy
  license_file: LICENSE.rst
  summary: 'Open source (the license is 100% compatible with bsd-3 clause)
    Python bindings to the ObjCryst++ crystallographic library.'
  doc_url: https://pyobjcryst.readthedocs.io/
  dev_url: https://github.com/diffpy/pyobjcryst

extra:
  recipe-maintainers:
    - Tieqiong
    - vincefn
    - pavoljuhas
    - st3107
    - sbillinge
