{% set name = "pyobjcryst" %}
{% set version = "2025.1.0" %}
{% set sha256 = "215ab4e4700e7eca23952e554ebcecc83cb6346d49072ed1c2f94c94fd27ad4d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - libobjcryst 2024.2.1
    - libboost-python-devel
  run:
    # NOTE libobjcryst is implicitly added by libobjcryst run_exports
    - python
    - setuptools
    - packaging

test:
  imports:
    - pyobjcryst
    - pyobjcryst.tests

about:
  home: https://github.com/diffpy/pyobjcryst
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python bindings to the ObjCryst++ crystallographic library.
  doc_url: https://pyobjcryst.readthedocs.io/
  dev_url: https://github.com/diffpy/pyobjcryst

extra:
  recipe-maintainers:
    - Tieqiong
    - vincefn
    - pavoljuhas
    - st3107
    - sbillinge
