{% set name = "pyobjcryst" %}
{% set version = "2.2.0" %}
{% set sha256 = "c02fda861db03b081e64320fdb1c14223137999d3ffc6d4cd322c333ea9cb975" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - libobjcryst 2021.1.1
    - boost
  run:
    # NOTE libobjcryst is implicitly added by libobjcryst run_exports
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - boost

test:
  imports:
    - pyobjcryst
    - pyobjcryst.tests

about:
  home: https://github.com/diffpy/pyobjcryst
  license: BNL
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Python bindings to the ObjCryst++ crystallographic library.'
  doc_url: http://diffpy.github.io/pyobjcryst
  dev_url: https://github.com/diffpy/pyobjcryst

extra:
  recipe-maintainers:
    - vincefn
    - pavoljuhas
    - st3107
    - sbillinge
