{% set name = "pyobjcryst" %}
{% set version = "2025.1.0rc.0" %}
{% set sha256 = "ba6e383abbee41aaf7d358daa3c86a066ef897423c0d68aca33218028b7ef9a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/refs/tags/2025.1.0-rc.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<311]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - numpy
  host:
    - python
    - pip
    - setuptools
    - setuptools-git-versioning
    - libboost-python-devel
    - libobjcryst
  run:
    - python
    - setuptools

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest

about:
  home: https://github.com/diffpy/pyobjcryst
  license: LicenseRef-diffpy
  license_file: LICENSE.rst
  summary: 'Open source (the license is 100% compatible with bsd-3 clause)
    Python bindings to the ObjCryst++ crystallographic library.'
  doc_url: https://pyobjcryst.readthedocs.io/
  dev_url: https://github.com/diffpy/pyobjcryst

extra:
  recipe-maintainers:
    - Tieqiong
    - vincefn
    - pavoljuhas
    - st3107
    - sbillinge
